title = "Muzeji in javnost"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "ananke"
###themesDir = "../.."

MetaDataFormat = "yaml"
DefaultContentLanguage = "sl"
SectionPagesMenu = "main"
Paginate = 20 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
summaryLength = 30

disqusShortname = "muzeji"



[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"



[languages]

  [languages.sl]
    title = "Muzeji in javnost"
    weight = 1

  [languages.en]
    title = "Museums and the public"
    weight = 2

[params]
  description = "O vrednotah družbeno odgovornih muzejev."
  #commentoEnable = true
  custom_css = ["css/custom.css"]

  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"

  # featured_image = "/images/muzeji-bg.jpg"

  background_color_class = "bg-dark-green"
  recent_posts_number = 100

